import { strokeFileName } from './strokes.ts'

/** A character's stroke data in the hanzi-writer-data format. */
export interface StrokeData {
  strokes: string[]
  medians: number[][][]
  radStrokes?: number[]
}

/**
 * Loads a character's strokes from public/strokes/ (generated by
 * `npm run data:build`). Requested when the entry page opens, not bundled.
 */
export async function loadStrokeData(hanzi: string, fetchFn: typeof fetch = fetch): Promise<StrokeData> {
  const response = await fetchFn(`${import.meta.env.BASE_URL}strokes/${strokeFileName(hanzi)}`)
  if (!response.ok) throw new Error(`No stroke data for ${hanzi} (HTTP ${response.status})`)
  return (await response.json()) as StrokeData
}
